#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 0.2.{build}
branches:
  only:
    - master
pull_requests:
  do_not_increment_build_number: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2019
nuget:
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#
before_build:
- cmd: nuget restore

build:
  publish_wap_octopus: true
  publish_nuget: true
  verbosity: minimal

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
#artifacts:
# pushing all *.nupkg files in build directory recursively
#  - path: '**\*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
- provider: NuGet
  api_key:
    secure: aghej3K2icV+eTZwMgUA64jKO6JwNL5VXGRvEPW0E/so6g1dvcrBfqz/w6EeD22l