# This script will make Appveyor to create a new build and execute the unit test
# whenever something is pushed to the master branch.
# By creating a release in Github with a version number following the scheme v1.0.0,
# it additionally pushes the Nuget packages to nuget.org and adds them to the release.

#---------------------------------#
#      General Configuration      #
#---------------------------------#
version: 0.6.23.{build}

branches:
  only:
    - master       # Release branch
#    - development
    - /v\d+\.\d+\.\d+/

pull_requests:
  do_not_increment_build_number: false

#---------------------------------#
#        Version Patching         #
#---------------------------------#
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

#---------------------------------#
#    Environment Configuration    #
#---------------------------------#
image: Visual Studio 2019

nuget:
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#
before_build:
- cmd: nuget restore

build:
  publish_nuget: true
  verbosity: minimal

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
#artifacts:
#  - path: \artifacts\*.*

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
# Refreshing key in Appveyor: Account > Encrypt YAML
deploy:
- provider: NuGet
  api_key:
    secure: GmeoMj+joMz9148pEjfMbZbBLyNZjUH7+MeOL6x6t4FxE3iLg75lNBChaGe/RD4O
  on:
    branch: master           # Deploy from release branch only
#    APPVEYOR_REPO_TAG: true  # Deploy builds with version tags only

- provider: GitHub
  release: "%APPVEYOR_REPO_TAG_NAME%"  #Do not change this or building will end in an infinite loop
  auth_token:
    secure: 1WaCyi/uL8oVBMCLlDopygdhRfEpFe2x7DcACaNtWHp8ueBrs8vJ8X/V13BEU7Xy
  on:
    branch: master           # Deploy from release branch only
#    APPVEYOR_REPO_TAG: true  # deploy on tag push only