#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 0.6.2

branches:
  only:
    - master       # Development branch
    - production   # Release branch

pull_requests:
  do_not_increment_build_number: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2019
nuget:
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#
before_build:
- cmd: nuget restore

build:
  publish_nuget: true
  verbosity: minimal

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
#artifacts:
#  - path: bin\package\*.*

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
# Refreshing key in Appveyor: Account > Encrypt YAML
deploy:

- provider: NuGet
  api_key:
    secure: GmeoMj+joMz9148pEjfMbZbBLyNZjUH7+MeOL6x6t4FxE3iLg75lNBChaGe/RD4O
  on:
    branch: production     # Release from production branch only

- provider: GitHub
  release: ES.Tools-{version}
  auth_token:
    secure: YtGsH7B9c6fUkDmOxoazOCRXN3Br4xZSMPJN8Bswuh3NiqIWqPc0opA+jkyqB9ZP
  on:
    branch: production     # Release from master branch only
