#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 0.5.0

#init:
#- ps: "Set-AppveyorBuildVariable -Name \"assembly_version\" -Value \"1.0\"  \nSet-AppveyorBuildVariable -Name \"assembly_file_version\" -Value \"1.0.0.0\"  \nSet-AppveyorBuildVariable -Name \"assembly_informational_version\" -Value \"1.0.0\""

branches:
  only:
    - master

pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: true
  file: SharedAssemblyInfo.*
  assembly_version: '${version}'
  assembly_file_version: '${version}'
  assembly_informational_version: '${version}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2019
nuget:
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#
before_build:
- cmd: nuget restore

build:
  publish_nuget: true
  verbosity: minimal

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
#artifacts:
#  - path: bin\package\*.*

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
# Refreshing key in Appveyor: Account > Encrypt YAML
deploy:
- provider: NuGet
  api_key:
    secure: GmeoMj+joMz9148pEjfMbZbBLyNZjUH7+MeOL6x6t4FxE3iLg75lNBChaGe/RD4O
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
- provider: GitHub
  release: ES.Tools-$(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: YtGsH7B9c6fUkDmOxoazOCRXN3Br4xZSMPJN8Bswuh3NiqIWqPc0opA+jkyqB9ZP
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
