# Name of the workflow
name: ES.WPF.Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setting up Nuget
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    # Restore Nuget packages
    - name: Restore Nuget packages
      run: nuget restore ES.WPF/ES.WPF/ES.WPF.sln
      
    # Setup MSBuild
    - name: Restore Nuget packages
      uses: warrenbuckley/Setup-MSBuild@v1
    
    #Build with MSBuild
    - name: Build
      run: msbuild  ES.WPF/ES.WPF/ES.WPF.sln -p:Configuration=Release
      
